# Generated by Django 2.2 on 2021-05-20 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndpointDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headers', models.TextField(blank=True, default='', help_text='headers associated with HTTP request')),
                ('body', models.TextField(blank=True, default='', help_text='Body data associated with HTTP request')),
                ('query_params', models.TextField(blank=True, default='', help_text='Query parameters associated with HTTP request')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.Endpoint', to_field='url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
