# Generated by Django 2.2 on 2021-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndpointDetails',
            new_name='EndpointDetail',
        ),
    ]
